language: bash
services: docker
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push yurissoares/spring-boot-api-lardosidosos;
    docker push yurissoares/mysql-api-lardosidosos;
  on:
    branch: desenvolvimento
notifications:
  email: false