version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lardosidosos?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: abcd
      DATABASE: lardosidosos
    networks:
      - common-network

  db:
    image: mysql
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: abcd
      MYSQL_DATABASE: lardosidosos
      MYSQL_PASSWORD: abcd
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
