package com.ufrb.lardosidosos.entity.enums;

public enum TipoDocumentoMorador {
	CPF, 
	RG,
	CTPS,
	TITULO_ELEITOR,
	PLANO_FUNERARIO,
	CERTIDAO_DE_NASCIMENTO,
	CERTIDAO_DE_CASAMENTO,
	CERTIDAO_DE_OBITO_DO_CONJUGE,
	CARTAO_DO_BENEFICIO,
	CARTAO_DO_SUS,
	CONTRATO;
}
